# Generated by Django 5.0.6 on 2024-07-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psqlapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
