# Generated by Django 5.0.6 on 2024-07-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psqlapp', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
    ]
