# Generated by Django 5.0.6 on 2024-07-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psqlapp', '0004_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
